// components/contribution-graph.tsx
"use client";

import { useMemo } from "react";
import type { Entry } from "@/lib/entries";

const GAP = 2;
const WEEKS = 52;
const DAYS = 7;

function getColor(count: number): string {
  if (count === 0) return "var(--contribution-0)";
  if (count === 1) return "var(--contribution-1)";
  if (count === 2) return "var(--contribution-2)";
  return "var(--contribution-3)";
}

export default function ContributionGraph({ entries }: { entries: Entry[] }) {
  const data = useMemo(() => {
    // Build a map of date string → entry count
    const countByDate = new Map<string, number>();
    for (const entry of entries) {
      // entry.id is like "2026-03-16" or "2026-03-16-timestamp"
      const dateKey = entry.id.slice(0, 10);
      countByDate.set(dateKey, (countByDate.get(dateKey) || 0) + 1);
    }

    // Build the grid: 52 weeks × 7 days, ending today
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const totalDays = WEEKS * 7;
    const grid: number[][] = [];

    for (let week = 0; week < WEEKS; week++) {
      const col: number[] = [];
      for (let day = 0; day < DAYS; day++) {
        const d = new Date(today);
        d.setDate(d.getDate() - (totalDays - 1 - (week * 7 + day)));
        const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
        col.push(countByDate.get(key) || 0);
      }
      grid.push(col);
    }

    return grid;
  }, [entries]);

  const cellSize = 10;
  const graphWidth = WEEKS * (cellSize + GAP) - GAP;
  const graphHeight = DAYS * (cellSize + GAP) - GAP;

  return (
    <div className="w-full">
      <svg
        viewBox={`0 0 ${graphWidth} ${graphHeight}`}
        className="block w-full h-auto"
        preserveAspectRatio="xMidYMid meet"
      >
        {data.map((week, wi) =>
          week.map((count, di) => (
            <rect
              key={`${wi}-${di}`}
              x={wi * (cellSize + GAP)}
              y={di * (cellSize + GAP)}
              width={cellSize}
              height={cellSize}
              rx={2}
              fill={getColor(count)}
            />
          ))
        )}
      </svg>

      {/* Legend */}
      <div className="flex items-center gap-1 mt-2 justify-end">
        <span className="text-[10px] text-[var(--muted)] mr-0.5">Less</span>
        {[0, 1, 2, 3].map((level) => (
          <div
            key={level}
            className="rounded-[2px]"
            style={{
              width: 10,
              height: 10,
              backgroundColor: getColor(level),
            }}
          />
        ))}
        <span className="text-[10px] text-[var(--muted)] ml-0.5">More</span>
      </div>
    </div>
  );
}

// src/lib/components/ContributionGraph.svelte
<script lang="ts">
	import { getEntriesPerDay } from '$lib/entries';
	import { journalEntries } from '$lib/journal';

	interface DayData {
		date: Date;
		count: number;
		key: string;
	}

	const entryCounts = $derived(getEntriesPerDay($journalEntries));

	function generateYearData(counts: Map<string, number>): DayData[] {
		const today = new Date();
		const days: DayData[] = [];

		const endDay = new Date(today);
		endDay.setDate(endDay.getDate() + (6 - endDay.getDay()));

		const startDay = new Date(endDay);
		startDay.setDate(startDay.getDate() - 52 * 7 + 1);

		for (let d = new Date(startDay); d <= endDay; d.setDate(d.getDate() + 1)) {
			const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
			const isFuture = d > today;
			const count = isFuture ? 0 : (counts.get(key) || 0);
			days.push({ date: new Date(d), count, key });
		}

		return days;
	}

	const cellSize = 14;
	const cellGap = 3;
	const cellRadius = 3;
	const step = cellSize + cellGap;

	const data = $derived(generateYearData(entryCounts));
	const weeks = $derived.by(() => {
		const grouped: DayData[][] = [];
		let currentWeek: DayData[] = [];

		for (const day of data) {
			if (day.date.getDay() === 0 && currentWeek.length > 0) {
				grouped.push(currentWeek);
				currentWeek = [];
			}
			currentWeek.push(day);
		}

		if (currentWeek.length > 0) grouped.push(currentWeek);
		return grouped;
	});

	const svgWidth = $derived(weeks.length * step);
	const svgHeight = 7 * step;

	function getColor(count: number): string {
		if (count === 0) return 'var(--contrib-0)';
		if (count === 1) return 'var(--contrib-1)';
		if (count === 2) return 'var(--contrib-2)';
		if (count >= 3) return 'var(--contrib-3)';
		return 'var(--contrib-0)';
	}
</script>

<div class="graph-container">
	<svg width="100%" viewBox="0 0 {svgWidth} {svgHeight}" class="graph-svg">
		{#each weeks as week, wi}
			{#each week as day}
				<rect
					x={wi * step}
					y={day.date.getDay() * step}
					width={cellSize}
					height={cellSize}
					rx={cellRadius}
					ry={cellRadius}
					fill={getColor(day.count)}
				>
					<title>{day.key}: {day.count} {day.count === 1 ? 'entry' : 'entries'}</title>
				</rect>
			{/each}
		{/each}
	</svg>

	<div class="legend">
		<span class="legend-label">Less</span>
		<span class="legend-cell" style="background: var(--contrib-0)"></span>
		<span class="legend-cell" style="background: var(--contrib-1)"></span>
		<span class="legend-cell" style="background: var(--contrib-2)"></span>
		<span class="legend-cell" style="background: var(--contrib-3)"></span>
		<span class="legend-label">More</span>
	</div>
</div>

<style>
	.graph-container {
		width: 100%;
	}

	.graph-svg {
		display: block;
	}

	.legend {
		display: flex;
		align-items: center;
		justify-content: flex-end;
		gap: 4px;
		margin-top: 10px;
	}

	.legend-label {
		font-size: 11px;
		color: var(--muted);
		padding: 0 2px;
	}

	.legend-cell {
		width: 12px;
		height: 12px;
		border-radius: 2.5px;
	}
</style>
