// components/sidebar.tsx
"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { House, BookOpen, MagnifyingGlass, PenNib, X, Sun, Moon, Monitor } from "@phosphor-icons/react";
import { UserButton, useAuth } from "@clerk/nextjs";
import { useWebHaptics } from "web-haptics/react";
import { useTheme } from "@/lib/theme-context";
import { useEntries } from "@/lib/entries-context";
import { moodLabel } from "@/lib/entries";
import Logo from "./logo";

function moodDot(score: number): string {
  if (score >= 9) return "bg-emerald-500";
  if (score >= 7) return "bg-sky-500";
  if (score >= 5) return "bg-amber-500";
  if (score >= 3) return "bg-orange-500";
  return "bg-red-500";
}

function SidebarEntriesSkeleton() {
  return (
    <div className="flex flex-col gap-[1px]">
      {Array.from({ length: 6 }).map((_, i) => (
        <div key={i} className="flex items-start gap-[7px] rounded-[5px] px-[7px] py-[4px]">
          <div className="skeleton h-[17px] w-[17px] rounded-[3px] mt-[2px] shrink-0" />
          <div className="flex flex-col gap-[4px] min-w-0 flex-1">
            <div className="skeleton h-[14px] w-[70%]" />
            <div className="skeleton h-[11px] w-[50%]" />
          </div>
        </div>
      ))}
    </div>
  );
}

export default function Sidebar() {
  const pathname = usePathname();
  const isHome = pathname === "/app";
  const isNew = pathname === "/app/new";
  const { userId } = useAuth();
  const { entries, isHydrated } = useEntries();
  const haptic = useWebHaptics();
  const { theme, setTheme } = useTheme();
  const [query, setQuery] = useState("");

  const filteredEntries = useMemo(() => {
    if (!query.trim()) return entries;
    const q = query.toLowerCase();
    return entries.filter(
      (e) =>
        e.date.toLowerCase().includes(q) ||
        e.dateShort.toLowerCase().includes(q) ||
        e.body.toLowerCase().includes(q) ||
        moodLabel(e.mood).toLowerCase().includes(q)
    );
  }, [entries, query]);

  return (
    <aside className="sidebar-chrome flex h-screen w-[240px] shrink-0 flex-col select-none">
      {/* Logo */}
      <div className="flex items-center px-4 pt-4 pb-3">
        <Logo />
      </div>

      {/* Search */}
      <div className="mx-3 mb-3">
        <div className="flex items-center gap-1.5 rounded-md bg-[var(--subtle)] px-2 py-[5px]">
          <MagnifyingGlass size={13} weight="regular" className="text-[var(--muted)] shrink-0" />
          <input
            type="text"
            placeholder="Search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="flex-1 bg-transparent text-[12px] text-[var(--foreground)] placeholder:text-[var(--muted)] outline-none"
          />
          {query && (
            <button onClick={() => { haptic.trigger("light"); setQuery(""); }} className="text-[var(--muted)] hover:text-[var(--foreground)]">
              <X size={11} weight="bold" />
            </button>
          )}
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex flex-1 flex-col overflow-y-auto px-2">
        {/* Home */}
        {!query && (
          <Link
            href="/app"
            className={`sidebar-item flex items-center gap-[7px] rounded-[5px] px-[7px] py-[3px] text-[13px] leading-[22px] font-normal text-left ${
              isHome ? "sidebar-item-active" : ""
            }`}
          >
            <House size={17} weight={isHome ? "fill" : "regular"} className={isHome ? "text-[var(--accent)]" : "text-[var(--muted)]"} />
            <span>Home</span>
          </Link>
        )}

        {/* Section header */}
        <div className={`${query ? "" : "mt-5"} mb-[3px] flex items-center px-[7px]`}>
          <span className="text-[11px] font-semibold uppercase tracking-wide text-[var(--muted)]">
            {query ? `Results (${filteredEntries.length})` : "Entries"}
          </span>
        </div>

        {/* New entry (if on /app/new) */}
        {isNew && !query && (
          <div className="sidebar-item sidebar-item-active flex items-start gap-[7px] rounded-[5px] px-[7px] py-[4px]">
            <PenNib size={17} weight="fill" className="mt-[2px] shrink-0 text-[var(--accent)]" />
            <div className="flex flex-col min-w-0">
              <span className="text-[13px] leading-[18px] truncate">New Entry</span>
              <span className="text-[11px] leading-[15px] text-[var(--muted)]">Draft</span>
            </div>
          </div>
        )}

        {/* Entries */}
        {!isHydrated ? <SidebarEntriesSkeleton /> : <div className="flex flex-col gap-[1px]">
          {filteredEntries.map((entry) => {
            const entryPath = `/app/entry/${entry.id}`;
            const isActive = pathname === entryPath;
            return (
              <Link
                key={entry.id}
                href={entryPath}
                className={`sidebar-item flex items-start gap-[7px] rounded-[5px] px-[7px] py-[4px] text-left transition-colors duration-100 ${
                  isActive ? "sidebar-item-active" : ""
                }`}
              >
                <BookOpen
                  size={17}
                  weight={isActive ? "fill" : "regular"}
                  className={`mt-[2px] shrink-0 ${isActive ? "text-[var(--accent)]" : "text-[var(--muted)]"}`}
                />
                <div className="flex flex-col min-w-0">
                  <span className="text-[13px] leading-[18px] truncate">{entry.dateShort}</span>
                  <span className="flex items-center gap-1">
                    <span className={`inline-block h-[6px] w-[6px] rounded-full ${moodDot(entry.mood)}`} />
                    <span className="text-[11px] leading-[15px] text-[var(--muted)]">
                      {moodLabel(entry.mood)} · {entry.mood}/10
                    </span>
                  </span>
                </div>
              </Link>
            );
          })}
        </div>}
      </nav>

      {/* Bottom */}
      <div className="shrink-0 px-3 pb-4 pt-2">
        <Link
          href="/app/new"
          className="flex w-full items-center gap-[7px] rounded-[5px] px-[7px] py-[3px] text-[13px] leading-[22px] font-normal text-[var(--accent)] transition-colors duration-100 hover:bg-[var(--sidebar-hover)] mb-2 cursor-default"
        >
          <PenNib size={17} weight="fill" />
          New Entry
        </Link>
        <div className="h-[0.5px] bg-[var(--divider)] mb-3" />
        <div className="flex items-center gap-1 px-1">
          <div className="flex-1 min-w-0">
            {userId ? (
              <UserButton
                showName
                appearance={{
                  elements: {
                    rootBox: "w-full",
                    userButtonTrigger: "w-full !justify-start",
                    userButtonBox: "!flex-row-reverse !gap-2",
                    userButtonOuterIdentifier: "!text-[12px] !text-[var(--foreground)] !font-normal !pl-0",
                    avatarBox: "!h-[22px] !w-[22px]",
                  },
                }}
              />
            ) : (
              <Link
                href="/sign-in"
                className="block truncate rounded-md px-2 py-1 text-[12px] text-[var(--muted)] transition-colors hover:bg-[var(--sidebar-hover)] hover:text-[var(--foreground)]"
              >
                Sign in to sync
              </Link>
            )}
          </div>
          <button
            onClick={() => {
              haptic.trigger("selection");
              const next = theme === "light" ? "dark" : theme === "dark" ? "system" : "light";
              setTheme(next);
            }}
            className="flex items-center justify-center rounded-md h-[26px] w-[26px] text-[var(--muted)] hover:bg-[var(--sidebar-hover)] hover:text-[var(--foreground)] transition-colors shrink-0"
            aria-label="Toggle theme"
            title={theme === "system" ? "Theme: System" : theme === "light" ? "Theme: Light" : "Theme: Dark"}
          >
            {theme === "light" ? <Sun size={14} /> : theme === "dark" ? <Moon size={14} /> : <Monitor size={14} />}
          </button>
        </div>
      </div>
    </aside>
  );
}

// src/lib/components/Sidebar.svelte
<script lang="ts">
	import {
		House,
		MagnifyingGlass,
		BookOpenText,
		PenNib,
		Sun,
		Moon,
		Desktop,
		SignOut,
		XCircle
	} from 'phosphor-svelte';
	import { cycleTheme, getTheme } from '$lib/theme.svelte';
	import { getMoodLabel, getMoodDotColor } from '$lib/entries';
	import { authClient } from '$lib/auth-client';
	import { triggerHaptic } from '$lib/haptics';
	import { journalEntries, journalLoaded, setJournalUser, syncStatus } from '$lib/journal';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import type { User } from 'better-auth';

	let { user } = $props<{ user: User | null }>();

	let searchQuery = $state('');
	let searchInput = $state<HTMLInputElement | null>(null);
	let isSigningOut = $state(false);

	const currentPath = $derived(page.url.pathname);
	const currentEntryId = $derived(page.params?.id ?? null);

	function stripHtml(html: string): string {
		return html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
	}

	const filteredEntries = $derived(() => {
		const q = searchQuery.trim().toLowerCase();
		if (!q) return $journalEntries;
		return $journalEntries.filter(
			(e) =>
				e.dateShort.toLowerCase().includes(q) ||
				e.date.toLowerCase().includes(q) ||
				getMoodLabel(e.mood).toLowerCase().includes(q) ||
				stripHtml(e.body).toLowerCase().includes(q)
		);
	});

	const initials = $derived(() => {
		const seed = user?.name?.trim() || user?.email?.trim() || 'S';
		return seed
			.split(/\s+/)
			.slice(0, 2)
			.map((part: string) => part[0]?.toUpperCase() ?? '')
			.join('');
	});

	const syncTone = $derived.by(() => {
		switch ($syncStatus.phase) {
			case 'synced':
				return 'synced';
			case 'syncing':
			case 'loading':
				return 'syncing';
			case 'offline':
				return 'offline';
			case 'error':
				return 'error';
			default:
				return $syncStatus.pendingCount > 0 ? 'syncing' : 'idle';
		}
	});

	const syncLabel = $derived.by(() => {
		switch ($syncStatus.phase) {
			case 'loading':
				return 'Loading local journal';
			case 'syncing':
				return $syncStatus.pendingCount > 0
					? `Syncing ${$syncStatus.pendingCount} change${$syncStatus.pendingCount === 1 ? '' : 's'}`
					: 'Syncing';
			case 'synced':
				return 'Synced';
			case 'offline':
				return $syncStatus.pendingCount > 0 ? 'Offline, changes queued' : 'Offline';
			case 'error':
				return $syncStatus.error ?? 'Sync paused';
			default:
				return $syncStatus.pendingCount > 0
					? `${$syncStatus.pendingCount} change${$syncStatus.pendingCount === 1 ? '' : 's'} queued`
					: 'Local first';
		}
	});

	async function signOut() {
		isSigningOut = true;
		triggerHaptic('light');

		const { error } = await authClient.signOut();

		if (!error) {
			await setJournalUser(null);
		}

		isSigningOut = false;

		if (!error) {
			await goto('/auth', { invalidateAll: true, replaceState: true });
		}
	}
</script>

<aside class="sidebar">
	<div class="sidebar-header">
		<a href="/" class="logo">Scribe</a>
	</div>

	<!-- Search -->
	<div class="search-wrapper">
		<MagnifyingGlass size={15} weight="regular" class="search-icon" />
		<input
			type="text"
			placeholder="Search"
			bind:value={searchQuery}
			bind:this={searchInput}
			class="search-input"
		/>
		{#if searchQuery}
			<button
				class="search-clear"
				onclick={() => {
					triggerHaptic('light');
					searchQuery = '';
					searchInput?.focus();
				}}
				aria-label="Clear search"
			>
				<XCircle size={14} weight="fill" />
			</button>
		{/if}
	</div>

	<!-- Home -->
	<a href="/" class="nav-item" class:active={currentPath === '/'} onclick={() => triggerHaptic('selection')}>
		<House size={18} weight={currentPath === '/' ? 'fill' : 'regular'} />
		<span>Home</span>
	</a>

	<!-- Entries section -->
	<div class="entries-section">
		<h3 class="entries-label">ENTRIES</h3>

		<div class="entries-list">
			{#if filteredEntries().length > 0}
				{#each filteredEntries() as entry (entry.id)}
					<a
						href="/entry/{entry.id}"
						class="entry-item"
						class:selected={currentEntryId === entry.id}
						onclick={() => triggerHaptic('selection')}
					>
						<div class="entry-row">
							<span class="entry-icon">
								<BookOpenText size={20} weight="regular" />
							</span>
							<div class="entry-details">
								<span class="entry-date">{entry.dateShort}</span>
								<div class="entry-mood">
									<span
										class="mood-dot"
										style="background-color: {getMoodDotColor(entry.mood)}"
									></span>
									<span class="mood-text">
										{getMoodLabel(entry.mood)} &middot; {entry.mood}/10
									</span>
								</div>
							</div>
						</div>
					</a>
				{/each}
			{:else if $journalLoaded}
				<p class="entries-empty">{searchQuery ? 'No matching entries.' : 'No journal entries yet.'}</p>
			{/if}
		</div>
	</div>

	<!-- Bottom section -->
	<div class="sidebar-bottom">
		<a href="/new" class="new-entry-btn" onclick={() => triggerHaptic('medium')}>
			<PenNib size={18} weight="fill" />
			<span>New Entry</span>
		</a>

		<div class="divider"></div>

		<div class="user-profile">
			<div class="user-avatar" aria-hidden="true">{initials()}</div>
			<div class="user-copy">
				<span class="user-name">{user?.name ?? 'Scribe user'}</span>
				<span class="user-email">{user?.email ?? ''}</span>
			</div>
			<button class="theme-btn" aria-label="Sign out" onclick={signOut} disabled={isSigningOut}>
				<SignOut size={16} weight="bold" />
			</button>
			<button
				class="theme-btn"
				aria-label="Switch theme ({getTheme()})"
				onclick={() => {
					triggerHaptic('selection');
					cycleTheme();
				}}
				title={getTheme() === 'light' ? 'Light' : getTheme() === 'dark' ? 'Dark' : 'System'}
			>
				{#if getTheme() === 'light'}
					<Sun size={16} weight="bold" />
				{:else if getTheme() === 'dark'}
					<Moon size={16} weight="bold" />
				{:else}
					<Desktop size={16} weight="bold" />
				{/if}
			</button>
		</div>

		<div class="sync-pill" title={syncLabel}>
			<span class="sync-dot {syncTone}"></span>
			<span>{syncLabel}</span>
		</div>
	</div>
</aside>

<style>
	.sidebar {
		width: 260px;
		min-width: 260px;
		height: 100dvh;
		display: flex;
		flex-direction: column;
		background-color: var(--sidebar-bg);
		backdrop-filter: saturate(180%) blur(20px);
		-webkit-backdrop-filter: saturate(180%) blur(20px);
		border-right: 0.5px solid var(--divider);
		padding: 16px 10px 10px;
		overflow: hidden;
		user-select: none;
		-webkit-user-select: none;
	}

	@media (max-width: 768px) {
		.sidebar {
			display: none;
		}
	}

	/* Logo */
	.sidebar-header {
		margin-bottom: 14px;
	}

	.logo {
		font-family: 'Instrument Serif', 'Georgia', serif;
		font-size: 28px;
		font-weight: 400;
		color: var(--foreground);
		text-decoration: none;
		display: block;
		margin-bottom: 6px;
		padding-left: 6px;
		letter-spacing: -0.3px;
	}

	.sync-pill {
		display: inline-flex;
		align-items: center;
		gap: 7px;
		padding: 0 6px;
		font-size: 11px;
		font-weight: 600;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: var(--muted);
	}

	.sync-dot {
		width: 7px;
		height: 7px;
		border-radius: 999px;
		background: color-mix(in srgb, var(--muted) 64%, transparent);
		box-shadow: 0 0 0 0 rgba(38, 132, 255, 0);
	}

	.sync-dot.synced {
		background: #22c55e;
	}

	.sync-dot.syncing {
		background: var(--accent);
		animation: sync-blip 1.4s ease-out infinite;
	}

	.sync-dot.offline {
		background: #f59e0b;
	}

	.sync-dot.error {
		background: #ef4444;
	}

	@keyframes sync-blip {
		0% {
			box-shadow: 0 0 0 0 color-mix(in srgb, var(--accent) 34%, transparent);
		}

		70% {
			box-shadow: 0 0 0 8px color-mix(in srgb, var(--accent) 0%, transparent);
		}

		100% {
			box-shadow: 0 0 0 0 color-mix(in srgb, var(--accent) 0%, transparent);
		}
	}

	/* Search — macOS Finder style */
	.search-wrapper {
		position: relative;
		margin-bottom: 10px;
	}

	.search-wrapper :global(.search-icon) {
		position: absolute;
		left: 8px;
		top: 50%;
		transform: translateY(-50%);
		color: var(--muted);
		pointer-events: none;
		z-index: 1;
	}

	.search-input {
		width: 100%;
		height: 30px;
		padding: 0 26px 0 28px;
		border-radius: 7px;
		border: 0.5px solid var(--divider);
		background: var(--search-bg);
		color: var(--foreground);
		font-size: 13px;
		font-family: inherit;
		outline: none;
		transition:
			background-color 0.2s,
			border-color 0.2s,
			box-shadow 0.2s;
	}

	.search-input::placeholder {
		color: var(--muted);
	}

	.search-input:focus {
		background: var(--search-bg-focus);
		border-color: var(--accent);
		box-shadow: 0 0 0 2.5px color-mix(in srgb, var(--accent) 25%, transparent);
	}

	.search-clear {
		position: absolute;
		right: 6px;
		top: 50%;
		transform: translateY(-50%);
		padding: 0;
		border: none;
		background: transparent;
		color: var(--muted);
		cursor: default;
		display: flex;
		align-items: center;
		justify-content: center;
		transition: color 0.1s;
		z-index: 1;
	}

	.search-clear:hover {
		color: var(--foreground);
	}

	/* Nav items — macOS sidebar style */
	.nav-item {
		display: flex;
		align-items: center;
		gap: 8px;
		width: 100%;
		padding: 6px 8px;
		border-radius: 7px;
		border: none;
		background: transparent;
		color: var(--foreground);
		font-size: 13px;
		font-weight: 500;
		font-family: inherit;
		cursor: default;
		transition: background-color 0.1s;
		text-align: left;
		text-decoration: none;
		line-height: 1.2;
	}

	.nav-item:hover {
		background: var(--hover-bg);
	}

	.nav-item.active {
		background: var(--active-bg);
		color: var(--foreground);
	}

	.nav-item.active :global(svg) {
		color: var(--accent);
	}

	/* Entries section */
	.entries-section {
		flex: 1;
		display: flex;
		flex-direction: column;
		margin-top: 16px;
		overflow: hidden;
		min-height: 0;
	}

	.entries-label {
		font-size: 11px;
		font-weight: 600;
		color: var(--muted);
		letter-spacing: 0.4px;
		text-transform: uppercase;
		margin-bottom: 4px;
		padding-left: 8px;
	}

	.entries-list {
		flex: 1;
		overflow-y: auto;
		overflow-x: hidden;
		scrollbar-width: none;
		mask-image: linear-gradient(to bottom, transparent 0%, black 4px, black calc(100% - 12px), transparent 100%);
		-webkit-mask-image: linear-gradient(to bottom, transparent 0%, black 4px, black calc(100% - 12px), transparent 100%);
	}

	.entries-list::-webkit-scrollbar {
		display: none;
	}

	.entries-empty {
		margin: 0;
		padding: 10px 8px;
		font-size: 12px;
		line-height: 1.5;
		color: var(--muted);
	}

	/* Entry item — compact macOS list style */
	.entry-item {
		display: block;
		width: 100%;
		padding: 7px 8px;
		border-radius: 7px;
		border: none;
		background: transparent;
		cursor: default;
		transition: background-color 0.1s;
		text-align: left;
		text-decoration: none;
		font-family: inherit;
		color: inherit;
	}

	.entry-item:hover {
		background: var(--hover-bg);
	}

	.entry-item.selected {
		background: var(--active-bg);
	}

	.entry-row {
		display: flex;
		align-items: flex-start;
		gap: 8px;
	}

	.entry-icon {
		color: var(--muted);
		margin-top: 1px;
		flex-shrink: 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.entry-details {
		display: flex;
		flex-direction: column;
		gap: 2px;
		min-width: 0;
	}

	.entry-date {
		font-size: 13px;
		font-weight: 600;
		color: var(--foreground);
		line-height: 1.3;
	}

	.entry-mood {
		display: flex;
		align-items: center;
		gap: 5px;
	}

	.mood-dot {
		width: 7px;
		height: 7px;
		border-radius: 50%;
		flex-shrink: 0;
	}

	.mood-text {
		font-size: 11.5px;
		color: var(--muted);
		line-height: 1.3;
	}

	/* Bottom section */
	.sidebar-bottom {
		margin-top: auto;
		padding-top: 6px;
		flex-shrink: 0;
	}

	.new-entry-btn {
		display: flex;
		align-items: center;
		gap: 8px;
		width: 100%;
		padding: 6px 8px;
		border-radius: 7px;
		border: none;
		background: transparent;
		color: var(--accent);
		text-decoration: none;
		font-size: 13px;
		font-weight: 500;
		font-family: inherit;
		cursor: default;
		transition: background-color 0.1s;
	}

	.new-entry-btn:hover {
		background: var(--hover-bg);
	}

	.divider {
		height: 0.5px;
		background: var(--divider);
		margin: 8px 6px;
	}

	.user-profile {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 5px 6px;
		border-radius: 7px;
		transition: background-color 0.1s;
	}

	.user-avatar {
		width: 28px;
		height: 28px;
		border-radius: 50%;
		flex-shrink: 0;
		box-shadow: 0 0 0 0.5px var(--divider);
		display: grid;
		place-items: center;
		background: color-mix(in srgb, var(--accent) 16%, var(--sidebar-bg));
		color: var(--accent);
		font-size: 11px;
		font-weight: 700;
		letter-spacing: 0.08em;
	}

	.user-copy {
		min-width: 0;
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: 1px;
	}

	.user-name {
		font-size: 13px;
		font-weight: 500;
		color: var(--foreground);
		flex: 1;
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.user-email {
		font-size: 11px;
		color: var(--muted);
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.theme-btn {
		padding: 4px;
		border: none;
		background: transparent;
		color: var(--muted);
		cursor: default;
		border-radius: 5px;
		display: flex;
		align-items: center;
		justify-content: center;
		transition:
			background-color 0.1s,
			color 0.1s;
		flex-shrink: 0;
	}

	.theme-btn:hover {
		background: var(--hover-bg);
		color: var(--foreground);
	}

	.theme-btn:active {
		background: var(--active-bg);
	}

	.theme-btn:disabled {
		opacity: 0.55;
	}
</style>
